### ISSUE TITLE
Secondary navigation

### ISSUE THREAD

**Issue by andreweick** [aeick/eick#10]
Could you put a secondary navigation?  I'm thinking like a the stuff you'd put in a footer nervation (not necessarily in the footer)

**Comment by andreweick** [comment]
maybe this is the footer text? 

You know, maybe we have the footer (like on the ABA site), and we also add a footer line on the right-hand-side column (for items global to that section) --

oh wait, where would those links go on the responsive-size breaks...

**Comment by budparr** [comment]
you can edit footer links in _data/footer-links.yaml
