### ISSUE TITLE
Add JSON as an data entry choice

### ISSUE THREAD

**Issue by budparr** [aeick/eick#20]
@andreweick I added the option to input your images via JSON file. This will open up some possibilities, including allowing you to have markdown copy and a gallery in the same post, and, as mentioned earlier, you won't have to write in links to your images to make them work in the gallery. 

Here's the post I converted to use JSON:
http://www.eick.us/family/2014/12/19/busy-week/

Here's the document for that post:
https://github.com/aeick/eick/blob/gh-pages/family/_posts/2014/2014-12-19-busy-week.md
Note that to match this up to the proper spot in the JSON file, I included this line in the front matter:
```images: "2014-12-19-busy-week"```  
and although that matches the file name it could be anything, as long as it matches an object in your JSON file (this will be more clear when you look at it, but ```images: foo``` in your document should match ```"foo":``` in your JSON file as an object encompassing your images). 

Here's the JSON file for all your images:
https://github.com/aeick/eick/blob/gh-pages/_data/images.json

Note that it's in the ```_data``` folder and you can just keep adding to that file, and, as you pointed out earlier, you can add more data to it. If you add the data to each image, we may have to adjust the model a bit because to avoid defining keys for each image I'm just pulling them up by their order (e.g. "```{{ image[1] }}```" is the url).

**Comment by budparr** [comment]
forgot to mention that the image names (essentially, the key for each) have to have unique names, which is why you see numbers after captions in that post. You can be more creative than adding a number after the name, of course.

**Comment by andreweick** [comment]
Oh my goodness you are fast.  I'm still trying to get my mind around the problem and you already have it checked in.  way cool.

**Comment by andreweick** [comment]
This is really neat, I'm have a bunch of ideas on how to use this.  Is there a way to have the JSON file be separate JSON files (named for the post) rather than 1 big file?

**Comment by budparr** [comment]
potentially, yes

**Comment by andreweick** [comment]
(btw, image names are unique identifiers for me, so no problem)

**Comment by budparr** [comment]
Cool. I'm walking out the door for the evening, but feel free to leave all the comments you like and I'll catch up by monday

**Comment by andreweick** [comment]
:100:
