### ISSUE TITLE
PDF viewer

### ISSUE THREAD

**Issue by andreweick** [aeick/eick#22]
I'm trying to add a PDF viewer -- I had thought I could add it similar to the "vimeo" tag in the front matter

Would I be adding logic similar to lines 20-25 in _layouts/post.html?

**Comment by budparr** [comment]
Can you put up an example?

**Comment by andreweick** [comment]
I've actually thought better of this also -- I was thinking of having an "embeded PDF view" with the PDF showing where the content shows, but now I don't think it's such a good idea and I should just have an external link to the document that people can either download or view i the browser (with just an <a link)
