### ISSUE TITLE
Add chromless page for resume

### ISSUE THREAD

**Issue by budparr** [aeick/eick#26]

**Comment by budparr** [comment]
@andreweick - I added  a page for you to post your resume without the menu. It also has a 'nofollow' designation in the header so pages in the CV (posts in the _cv folder) collection won't be indexed by search engines.  Tell me how you want this page to look and I'll finish it up. Also, if you don't want the URL to be /cv/, let me know. It can, of course, be anything you like. 

http://www.eick.us/cv/eick/

**Comment by andreweick** [comment]
Excellent
