### ISSUE TITLE
Ipad mini layout landcape

### ISSUE THREAD

**Issue by andreweick** [aeick/eick#27]
Seems to be a weird layout / break bug on iPad (mini, haven't tried iPad big) -- 
![img_0340](https://cloud.githubusercontent.com/assets/1289435/7255013/8e512086-e814-11e4-95ac-d2bcc92c98a3.PNG)
![img_0339 2](https://cloud.githubusercontent.com/assets/1289435/7255017/91d6b086-e814-11e4-8cfd-32d64eb7a656.PNG)

**Comment by budparr** [comment]
Ah, I think I introduced this when I added the archive>category links to the mobile menu. Looks like a breakpoint issue.
