### ISSUE TITLE
snapshot color tile?

### ISSUE THREAD

**Issue by andreweick** [aeick/eick#30]
Can you tweak the "snapshot" tile color (upper right hand corner) to be a bit more opposing to stand out (but blend) with the others?

**Comment by budparr** [comment]
do you mean you want to change the red?

**Comment by andreweick** [comment]
Not the red, it's like an almost black color (maybe charcoal?)
![napkin 2 04-21-15 5 08 41 pm](https://cloud.githubusercontent.com/assets/1289435/7262611/0d4dcbee-e849-11e4-9701-df4537ecfd86.png)

**Comment by budparr** [comment]
Oh, right. I gave them all different colors to differentiate the various categories. I'll pick something else.

**Comment by budparr** [comment]
I changed this. You can re-open the issue if you want it to something else, and if you ever feel like changing it to something else, the colors are in ```/assets/css/_sass/modules/_sidebar-headings-and-colors.scss```
